workspace:
  base: /drone
  path: src

branches: [ master ]

pipeline:
  dryrun:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloudci/base
    build_args:
      - PHP_VERSION=${PHP_VERSION}
    label_schema:
      - version=${PHP_VERSION}
    dry_run: true
    tags: [ '${PHP_VERSION}' ]
    when:
      event: [ pull_request ]

  docker:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloudci/base
    build_args:
      - PHP_VERSION=${PHP_VERSION}
    label_schema:
      - version=${PHP_VERSION}
    tags: [ '${PHP_VERSION}' ]
    when:
      event: [ push ]

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets:
      - source: microbadger_token
        target: plugin_webhook
    when:
      event: [ push ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: drone
    when:
      status: [ success, failure ]

matrix:
  PHP_VERSION:
    - latest
    - 5.6
    - 7.0
    - 7.1
    - 7.2